spring:
  application:
    name: springcase-datasource
  jdbc:
    username: root
    password: 123456
    driverClass: com.mysql.jdbc.Driver
    write:
      url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=true
    read:
      url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=true
mybatis:
  type-aliases-package: com.zhang.springcase.dao.*
  mapper-locations: classpath:/mappers/*Mapper.xml